config/routes.rb
Sdm001::Application.routes.draw do
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	resources :m_ordinary_publishers  
	resources :m_ordinary_channels
	resources :m_ordinary_positions
	

  
	root to: 'sessions#new'
	match '/signin', to: 'sessions#new', via: 'get'
	match '/signout', to: 'sessions#destroy', via: 'delete'
	match '/create_ordinary_publisher', to: 'm_ordinary_publishers#new', via: 'get'
	match '/edit_m_ordinary_channel', to: 'm_ordinary_channels#edit', via: 'get'
	match '/edit_m_ordinary_position', to: 'm_ordinary_positions#edit', via: 'get'
	

end

app/models/m_ordinary_publisher.rb
class MOrdinaryPublisher < ActiveRecord::Base	
	has_many :m_ordinary_channels, dependent: :destroy
	before_save do
		self.name = name.downcase
		self.url = url.downcase
	end
	validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
	validates :url, presence: true
	
	def self.search(type, keywords)
		if type and keywords and !keywords.empty?
			if type == 'id'
				find(:all, conditions: ['id = ?', keywords.to_i])
			elsif type == 'name'
				find(:all, conditions: ['name LIKE ?', "%#{keywords}%"])
			else
				find(:all)
			end
		else
			find(:all)
		end
	end

#	def self.update(id, options = {})
#		update(id, { name: options[:name], url: options[:url], 
#					state_id: options[:state_id], user_id: options[:user_id] })
#	end
end

app/controllers/m_ordinary_publishers_controller.rb
class MOrdinaryPublishersController < ApplicationController
	def index
		if params[:per_page]
			@per_page = params[:per_page]
		else
			@per_page = 10
		end
#		@m_ordinary_publishers = MOrdinaryPublisher.paginate(page: params[:page], per_page: @per_page)
		@m_ordinary_publishers = MOrdinaryPublisher.paginate(page: params[:page], per_page: @per_page).search(params[:search_type], params[:search])
	end

	def new
		@publisher = MOrdinaryPublisher.new
	end

	def show
		@publisher = MOrdinaryPublisher.find(params[:id])
	end

	def edit
		@publisher = MOrdinaryPublisher.find(params[:id])
	end

	def create
		@to_be_insert = { name: params[:m_ordinary_publisher][:name], 
										 url: params[:m_ordinary_publisher][:url],
										 state_id: MState.find_by(name: params[:m_ordinary_publisher][:state_id]).id,
										 created_user_id: User.find_by(name: current_user.name).id, 
										 modified_user_id: User.find_by(name: current_user.name).id }
		@publisher = MOrdinaryPublisher.new(@to_be_insert)
		if @publisher.save
			flash[:success] = "Create publisher success!"
			redirect_to m_ordinary_publishers_path
		else
			render 'new'
		end
	end	

	def update
		@publisher = MOrdinaryPublisher.find(params[:id])	

		MOrdinaryPublisher.update(params[:id], 
										name: params[:m_ordinary_publisher][:name],
										url: params[:m_ordinary_publisher][:url],
										state_id: MState.find_by(name: params[:m_ordinary_publisher][:state_id]).id,
										modified_user_id: User.find_by(name: current_user.name).id )

#		if @publisher.update_attributes(publisher_params)	
			flash[:success] = "Profile updated"
			redirect_to m_ordinary_publishers_path
#		else
#			redirect_to root_path
#		end
	end

	def destroy
		MOrdinaryPublisher.find(params[:id]).destroy
		flash[:success] = "Publisher destroyed."
		session[:return_to] ||= request.referer	
		redirect_to session.delete(:return_to)
	end

	private

	def publisher_params
		params.require(:m_ordinary_publisher).permit(:name, :url, :state_id)
	end

end

app/helpers/m_ordinary_publishers_helper.rb
module MOrdinaryPublishersHelper
end

app/views/m_ordinary_publishers/_publishers.html.erb
<table class="table">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Url</th>
			<th>State</th>
			<th>channel number</th>
			<th>position number</th>
			<th>Modified User</th>
			<th>Modified Time</th>
			<th>Operation</th>
		</tr>
	</thead>
	<tbody>
	<% @m_ordinary_publishers.each do |publisher| %>
		<tr>
			<td><%= publisher.id %></td>
			<td><%= link_to publisher.name, { controller: "m_ordinary_channels", action: :index, publisher_id: publisher.id } %></td>
			<td><%= publisher.url %></td>
			<td><%= MState.find_by(id: publisher.state_id).name %></td>
			<td><%= MOrdinaryChannel.find(:all, conditions: ['m_ordinary_publisher_id = ?', publisher.id]).size %></td>
			<td><%= MOrdinaryPosition.find(:all, conditions: ['m_ordinary_publisher_id = ?', publisher.id]).size %></td>
			<td><%= User.find_by(id: publisher.modified_user_id).name %></td>
			<td><%= publisher.updated_at %></td>
			<td><%= link_to "Update", edit_m_ordinary_publisher_path(publisher) %> 
					| 
					<%= link_to "Delete", { controller: "m_ordinary_publishers", action: :destroy, id: publisher.id },
																{ confirm: "Are you sure?", method: :delete } %>
			</td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/m_ordinary_publishers/edit.html.erb
<% provide(:title, 'Edit Publisher') %>
<h1>Edit publisher</h1>
	<%= form_for(@publisher) do |f| %>
		<%= render 'shared/error_messages' %>

		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :url %>
		<%= f.text_field :url %>
	
		<%= f.label :state %>	
		<%= f.select :state_id, options_for_select(MState.all.collect { |state| state.name })  %>	

		<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
	<% end %>

app/views/m_ordinary_publishers/index.html.erb
<% provide(:title, 'ordinary publishers') %>
<h1>Ordinary Publishers</h1>

<%#= select_tag :itemNum, options_from_collection_for_select(ItemNum.all, 'id', 'num'), include_blank: false, style: "width:70px" , onchange: "if(this.value){window.location='?num='+this.value;}"%>
<%= select_tag :per_page, options_for_select(PerPage.all.collect { |items| items.per_page }, @per_page.to_i), :onchange => "if(this.value){window.location='?per_page='+this.value;}", style: "width: 70px" %>
<%#= select_tag :search_type, options_for_select(['id', 'name']), :onchange => "if(this.value){window.location='?search_type='+this.value;}", style: "width: 70px" %>
<%#= select "ItemNum", "num", ItemNum.all.collect { |item| [item.num, item.id] },  include_blank: false %>
<%= form_tag m_ordinary_publishers_path, method: :get do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", name: nil %>
	</p>
<% end %>
<%= link_to "Create publisher", create_ordinary_publisher_path, class: "btn btn-primary" %>
<%= will_paginate %>
<%= render 'publishers' %>
<%= will_paginate %>

app/views/m_ordinary_publishers/new.html.erb
<% provide(:title, 'Create publisher') %>
<h1>Create publisher</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@publisher) do |f| %>
			<%= render 'shared/publisher_error_messages' %>
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :url %>
			<%= f.text_field :url %>

			<%= f.label :state %>	
			<%= f.select :state_id, options_for_select(MState.all.collect { |state| state.name })  %>	

			<%= f.submit "Create publisher", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>