config/routes.rb
Sdm001::Application.routes.draw do
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	resources :m_ordinary_publishers  
	resources :m_ordinary_channels
	resources :m_ordinary_positions
	

  
	root to: 'sessions#new'
	match '/signin', to: 'sessions#new', via: 'get'
	match '/signout', to: 'sessions#destroy', via: 'delete'
	match '/create_ordinary_publisher', to: 'm_ordinary_publishers#new', via: 'get'
	match '/edit_m_ordinary_channel', to: 'm_ordinary_channels#edit', via: 'get'
	match '/edit_m_ordinary_position', to: 'm_ordinary_positions#edit', via: 'get'
	

end

app/models/m_ordinary_channel.rb
class MOrdinaryChannel < ActiveRecord::Base
	belongs_to :publisher
	has_many :m_ordinary_positions, dependent: :destroy
	before_save do
		self.name = name.downcase
		self.url = url.downcase
	end
	validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
	validates :url, presence: true
	
	def self.search(type, keywords)
		if type and keywords and !keywords.empty?
			if type == 'id'
				find(:all, conditions: ['id = ?',  keywords.to_i])
			elsif type == 'name'
				find(:all, conditions: ['name LIKE ?', "%#{keywords}%"])
			else
				find(:all)
			end
		else
			find(:all)
		end
	end

end

app/controllers/m_ordinary_channels_controller.rb
class MOrdinaryChannelsController < ApplicationController
	def index
		if params[:per_page]
			@per_page = params[:per_page]
		else
			@per_page = 10
		end
		gon.publisher_id = params[:publisher_id]
#		if @id == nil
#			@id = 302
#		end
#		@m_ordinary_channels = MOrdinaryChannle.paginate(page: params[:page], per_page: @per_page)
#		@m_ordinary_channels = MOrdinaryChannel.paginate(page: params[:page], per_page: @per_page).search(params[:search])
		@publisher = MOrdinaryPublisher.find(params[:publisher_id])
		@m_ordinary_channels = @publisher.m_ordinary_channels.paginate(page: params[:page], per_page: @per_page).search(params[:search_type], params[:search])
#		redirect_to m_ordinary_channels_path, id: @id
	end

	def new
		@channel = MOrdinaryChannel.new
	end

	def show
		@channel = MOrdinaryChannel.find(params[:id])
	end

	def edit
		@channel = MOrdinaryChannel.find(params[:id])
	end

	def create
		@to_be_insert = { name: params[:m_ordinary_channel][:name], 
										 url: params[:m_ordinary_channel][:url],
										 state_id: MState.find_by(name: params[:m_ordinary_channel][:state_id]).id,
										 created_user_id: User.find_by(name: current_user.name).id, 
										 modified_user_id: User.find_by(name: current_user.name).id,
										 m_ordinary_publisher_id: params[:publisher_id].to_i }
		@channel = MOrdinaryChannel.new(@to_be_insert)
		if @channel.save
			flash[:success] = "Create channel success!"
			redirect_to action: :index, publisher_id: params[:publisher_id]
#			redirect_to action: "new", id: params[:id]
		else
			render action: :new, publisher_id: params[:publisher_id]
#			render new_m_ordinary_channel_path(publisher_id: params[:publisher_id])
		end
	end	

	def update
		@channel = MOrdinaryChannel.find(params[:id])	

		MOrdinaryChannel.update(params[:id], 
										name: params[:m_ordinary_channel][:name],
										url: params[:m_ordinary_channel][:url],
										state_id: MState.find_by(name: params[:m_ordinary_channel][:state_id]).id,
										modified_user_id: User.find_by(name: current_user.name).id )

#		if @publisher.update_attributes(publisher_params)	
			flash[:success] = "Channel updated"
			redirect_to action: :index, publisher_id: params[:publisher_id]
#		else
#			redirect_to root_path
#		end
	end

	def destroy
		MOrdinaryChannel.find(params[:id]).destroy
		flash[:success] = "Channel destroyed."
		session[:return_to] ||= request.referer	
		redirect_to session.delete(:return_to)
	end

	private

	def publisher_params
		params.require(:m_ordinary_channel).permit(:name, :url, :state_id)
	end


end

app/helpers/m_ordinary_channels_helper.rb
module MOrdinaryChannelsHelper
end

app/views/m_ordinary_channels/_channels.html.erb
<table class="table">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Url</th>
			<th>State</th>
			<th>position number</th>
			<th>Modified User</th>
			<th>Modified Time</th>
			<th>Operation</th>
		</tr>
	</thead>
	<tbody>
	<% @m_ordinary_channels.each do |channel| %>
		<tr>
			<td><%= channel.id %></td>
			<td><%= link_to channel.name, m_ordinary_positions_path(publisher_id: params[:publisher_id], channel_id: channel.id) %></td>
			<td><%= channel.url %></td>
			<td><%= MState.find_by(id: channel.state_id).name %></td>
			<td><%= MOrdinaryPosition.find(:all, conditions: ['m_ordinary_channel_id = ?', channel.id]).size %></td>
			<td><%= User.find_by(id: channel.modified_user_id).name %></td>
			<td><%= channel.updated_at %></td>
			<td><%= link_to "Update", "/m_ordinary_channels/#{channel.id}/edit?publisher_id=#{params[:publisher_id]}" %> 
					| 
					<%= link_to "Delete", { controller: "m_ordinary_channels", action: :destroy, id: channel.id },
																{ confirm: "Are you sure?", method: :delete } %>
			</td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/m_ordinary_channels/edit.html.erb
<% provide(:title, 'Edit Publisher') %>
<h1>Edit channel</h1>
	<%= form_for(@channel) do |f| %>
		<%= render 'shared/channel_error_messages' %>

		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :url %>
		<%= f.text_field :url %>
	
		<%= f.label :state %>	
		<%= f.select :state_id, options_for_select(MState.all.collect { |state| state.name })  %>	

		<%= hidden_field_tag :publisher_id, params[:publisher_id] %>

		<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
	<% end %>

app/views/m_ordinary_channels/index.html.erb
<% provide(:title, 'ordinary channels') %>
<h1>Ordinary Channels</h1>

<%#= select_tag :itemNum, options_from_collection_for_select(ItemNum.all, 'id', 'num'), include_blank: false, style: "width:70px" , onchange: "if(this.value){window.location='?num='+this.value;}"%>
<%= select_tag :per_page, options_for_select(PerPage.all.collect { |items| items.per_page }, @per_page.to_i), onchange: "if(this.value){window.location='?per_page='+this.value+'&publisher_id='+gon.publisher_id;}", style: "width: 70px" %>
<%#= select_tag :search_type, options_for_select(['id', 'name']), :onchange => "if(this.value){window.location='?search_type='+this.value;}", style: "width: 70px" %>
<%#= select "ItemNum", "num", ItemNum.all.collect { |item| [item.num, item.id] },  include_blank: false %>
<%= form_tag m_ordinary_channels_path, method: :get do %>
	<p>
		<%= select_tag :search_type, options_for_select(['id', 'name']) %>
		<%= text_field_tag :search, params[:search] %>
		<%= hidden_field_tag :publisher_id, params[:publisher_id] %>
		<%= submit_tag "Search", name: nil %>
	</p>
<% end %>
<%= link_to "Create channel", { controller: "m_ordinary_channels", action: :new , publisher_id: params[:publisher_id]} %>
<%= will_paginate %>
<%= render 'channels' %>
<%= will_paginate %>

app/views/m_ordinary_channels/new.html.erb
<% provide(:title, 'Create channel') %>
<h1>Create channel</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@channel) do |f| %>
			<%= render 'shared/channel_error_messages' %>
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :url %>
			<%= f.text_field :url %>

			<%= f.label :state %>	
			<%= f.select :state_id, options_for_select(MState.all.collect { |state| state.name })  %>

			<%= hidden_field_tag :publisher_id, params[:publisher_id] %>

			<%= f.submit "Create channel", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>