config/routes.rb
Sdm001::Application.routes.draw do
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	resources :m_ordinary_publishers  
	resources :m_ordinary_channels
	resources :m_ordinary_positions
	

  
	root to: 'sessions#new'
	match '/signin', to: 'sessions#new', via: 'get'
	match '/signout', to: 'sessions#destroy', via: 'delete'
	match '/create_ordinary_publisher', to: 'm_ordinary_publishers#new', via: 'get'
	match '/edit_m_ordinary_channel', to: 'm_ordinary_channels#edit', via: 'get'
	match '/edit_m_ordinary_position', to: 'm_ordinary_positions#edit', via: 'get'
	

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Suning Digital Marketing", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", '#' %></li>
					<% if signed_in? %>
						<li><%= link_to "Users", '#' %></li>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Media Management <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Ordinary Media", '#' %></li>
								<li><%= link_to "Search engine", '#' %></li>
								<li><%= link_to "Alliance", '#' %></li>
								<li class="divider"></li>
								<li>
									<%= link_to "Sign out", signout_path, method: "delete" %>
								</li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
	<%= include_gon %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
	
</head>
<body>
	<%= render 'layouts/header' %>	
	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>